---
apiVersion: v1
kind: Secret
metadata:
  name: suxess-it-dev-poi-map-app-repo
  namespace: suxess-it-admin
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/phac008/suxess-it-dev-frontend-gitops
